Web interface
oleverse/picturest pull request #26
Opened 2023-07-28 12:58 UTC by iPhenomenom

налагодив аунтифікацію та домашню сторінку

2023-07-28 13:49 UTC, oleverse requested changes
Треба окремо нам з тобою зібратися і помізкувати.

2023-07-28 13:49 UTC, oleverse commented on api/routes/auth.py
Не можна перенаправляти користувача на головну сторінку зсередини API маршруту. Як це перенаправлення буде працювати, якщо ми будемо не браузером звертатися, а стороннім сервісом? Для такого перенаправлення повинен існувати окремий роут у складі web_response.router

2023-07-28 13:49 UTC, oleverse commented on api/repository/web_service.py
Навіщо цей файл? Ми ж маємо вже такий функціонал десь в auth!

2023-07-28 13:49 UTC, oleverse commented on front/templates/js/main.js
Це цікаво!

2023-07-28 13:49 UTC, oleverse commented on front/templates/upload.html
> +        <form action="/create_picture" method="post" enctype="multipart/form-data" class="mt-4">
А де сам роут create_picture?

2023-07-28 22:01 UTC, closed without merging

2023-07-29 11:10 UTC, iPhenomenom commented
сьогодні можемо посидіти поміркувати